const {
  USERS_COLLECTION_NAME,
  GROUPS_COLLECTION_NAME,
  ACTIVE_USERS_COLLECTION_NAME,
  ACCOUNTS_COLLECTION_NAME,
  TRANSACTIONS_COLLECTION_NAME,
  INVOICES_COLLECTION_NAME,
  INVENTORIES_COLLECTION_NAME,
  BANK_TRANSACTIONS_COLLECTION_NAME
} = require("./database-constants");

const {
  TOKEN_ALGORITHM,
  TOKEN_VALIDITY,
  TOKEN_PUBLIC_KEY,
  TOKEN_PRIVATE_KEY,
  AUTHORIZATION_HEADER,
} = require("./authentication-constants");

const {FileFormats} = require('./file-constants');

module.exports = {
  USERS_COLLECTION_NAME,
  GROUPS_COLLECTION_NAME,
  ACTIVE_USERS_COLLECTION_NAME,
  ACCOUNTS_COLLECTION_NAME,
  TRANSACTIONS_COLLECTION_NAME,
  INVOICES_COLLECTION_NAME,
  INVENTORIES_COLLECTION_NAME,
  BANK_TRANSACTIONS_COLLECTION_NAME,
  TOKEN_ALGORITHM,
  TOKEN_VALIDITY,
  TOKEN_PUBLIC_KEY,
  TOKEN_PRIVATE_KEY,
  AUTHORIZATION_HEADER,
  FileFormats
};
